spring:
  rabbitmq:
    host: 10.66.66.17  # rabbitMQ server IP   127.0.0.1
#    host: localhost  # rabbitMQ server IP   127.0.0.1
    port: 5672       # rabbitMQ server port
    username: admin
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5

server:
  port: 8091
  servlet:
    context-path: /consumer

## rabbitMQ properties ,the name as you like
mq:
  config:
    exchange: log.direct  # 交换器的名称
    queue:
      info:
        value: log.info  # 服务名称
        routing-key: log.info.routing.key # info路由键

